engines:
  # https://github.com/rubysec/bundler-audit
  bundler-audit:
    enabled: true

  # http://www.coffeelint.org/#options
  coffeelint:
    enabled: true

  # https://github.com/codeclimate/codeclimate-fixme
  fixme:
    enabled: true

  # https://github.com/brigade/scss-lint#configuration
  scss-lint:
    enabled: true

ratings:
  paths:
    - '**.coffee'
    - '**.sass'
    - Gemfile.lock

exclude_paths:
  - vendor
